covid19datahub: Finalist
phillips-et-al-nCovForecast: Finalist
fitzgerald-hanly-churches-covoid-simulation-modelling: Finalist
trendecon: Finalist
hahn-covid-shinyline: Finalist
laurinec-CoronaDash: Finalist
bulletin-board-japan: Finalist
john-coene: Finalist
mingione-nowcasting: Finalist
shubhrampandey-covid19-monitor: Finalist
covid19-sir-model: Finalist
pangea-Covid19: Finalist
danese-covid19-understanding: Finalist
eric-covid19ke: Finalist
kode-mint: Finalist
